apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: atlantis
  namespace: argocd
spec:
  destinations:
  - name: in-cluster
    namespace: '*'
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - https://runatlantis.github.io/helm-charts
  - https://github.com/bentastic27/homelab-iac.git
