apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: knative
  namespace: argocd
spec:
  destinations:
  - name: in-cluster
    namespace: '*'
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - https://github.com/knative/*
  - https://github.com/bentastic27/homelab-iac.git