apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: prometheus
  namespace: argocd
spec:
  destinations:
  - name: in-cluster
    namespace: '*'
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - https://prometheus-community.github.io/helm-charts
