apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atlantis
  namespace: argocd
spec:
  project: atlantis
  source:
    chart: atlantis
    repoURL: https://runatlantis.github.io/helm-charts
    targetRevision: 5.5.0
    helm:
      valuesObject:
        replicaCount: 1
        github:
          user: bentastic27
        orgAllowlist: github.com/bentastic27/*
        vcsSecretName: atlantis-vcs
        basicAuthSecretName: atlantis-creds
        awsSecretName: aws-creds
        service:
          type: ClusterIP
        volumeClaim:
          storageClassName: openebs-hostpath
        ingress:
          path: /
          ingressClassName: nginx
          host: atlantis.beansnet.net
          tls:
          - hosts:
            - atlantis.beansnet.net
            secretName: atlantis-cert-secret
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
            kubernetes.io/tls-acme: "true"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: atlantis
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        istio.io/dataplane-mode: ambient
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atlantis-manifests
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: atlantis
  source:
    path: argocd/manifests/atlantis
    repoURL: https://github.com/bentastic27/homelab-iac.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
