apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cpu-requests-remover-webhook
  namespace: argocd
spec:
  project: system
  destination:
    server: https://kubernetes.default.svc
    namespace: cpu-requests-remover-webhook
  source:
    repoURL: https://github.com/bentastic27/cpu-requests-remover-webhook.git
    path: config
    targetRevision: HEAD
  syncPolicy:
    automated: {}