apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argocd
spec:
  project: istio
  sources:
  - chart: istio-base
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.23.0
    helm:
      releaseName: istio-base
  - chart: istiod
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.23.0
    helm:
      releaseName: istiod
  destination:
    server: "https://kubernetes.default.svc"
    namespace: istio-system
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
