apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base
  namespace: argocd
spec:
  project: system
  source:
    chart: base
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.23.0
  destination:
    server: "https://kubernetes.default.svc"
    namespace: istio-system
  syncPolicy:
#    automated: {}
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: argocd
spec:
  project: system
  source:
    chart: istiod
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.23.0
  destination:
    server: "https://kubernetes.default.svc"
    namespace: istio-system
  syncPolicy:
#    automated: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingress
  namespace: argocd
spec:
  project: system
  source:
    chart: gateway
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.23.0
    helm:
      valuesObject:
        defaults:
          service:
            type: NodePort
  destination:
    server: "https://kubernetes.default.svc"
    namespace: istio-system
  syncPolicy:
#    automated: {}
