apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knative-ddns-route53
  namespace: argocd
spec:
  project: system
  destination:
    server: https://kubernetes.default.svc
    namespace: knative-ddns-route53
  source:
    repoURL: https://github.com/bentastic27/knative-route53-ddns.git
    path: k8s-manifests
    targetRevision: HEAD
  syncPolicy:
    automated: {}
