apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knative-operator
  namespace: argocd
spec:
  project: knative
  destination:
    server: https://kubernetes.default.svc
    namespace: knative-operator
  source:
    repoURL: https://github.com/bentastic27/homelab-iac.git
    path: argocd/manifests/knative
    targetRevision: HEAD
    directory:
      include: operator.yaml
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
    automated: {}
  ignoreDifferences:
  - group: rbac.authorization.k8s.io/
    kind: ClusterRole
    jsonPointers: /rules
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knative-serving
  namespace: argocd
spec:
  project: knative
  destination:
    server: https://kubernetes.default.svc
    namespace: knative-serving
  source:
    repoURL: https://github.com/bentastic27/homelab-iac.git
    path: argocd/manifests/knative
    targetRevision: HEAD
    directory:
      include: serving.yaml
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    # automated: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knative-eventing
  namespace: argocd
spec:
  project: knative
  destination:
    server: https://kubernetes.default.svc
    namespace: knative-eventing
  source:
    repoURL: https://github.com/bentastic27/homelab-iac.git
    path: argocd/manifests/knative
    targetRevision: HEAD
    directory:
      include: eventing.yaml
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    # automated: {}