apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs
  namespace: argocd
spec:
  project: system
  source:
    chart: openebs
    repoURL: https://openebs.github.io/charts
    targetRevision: 3.10.0
    helm:
      releaseName: openebs
      valuesObject:
        localprovisioner:
          enabled: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: openebs
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
