apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: prometheus
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: "62.6.0"
    helm:
      releaseName: kube-prometheus-stack
      valuesObject:
        crds:
          enabled: true
        grafana:
          persistence:
            enabled: true
            type: sts
            accessModes:
            - ReadWriteOnce
            size: 20Gi
            storageClassName: openebs-hostpath
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
