apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secret-syncopier
  namespace: argocd
spec:
  project: system
  destination:
    server: https://kubernetes.default.svc
    namespace: secret-syncopier
  source:
    repoURL: https://github.com/bentastic27/k8s-secret-syncopier.git
    path: install
    targetRevision: HEAD
  syncPolicy:
    automated: {}