apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-installation
  namespace: argocd
spec:
  project: argocd
  source:
    chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 7.7.14
    helm:
      releaseName: argocd
      valuesObject:
        configs:
          params:
            server.insecure: true
        redisSecretInit:
          podLabels:
            sidecar.istio.io/inject: "false"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        istio-injection: enabled
