apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  ingress:
    kourier:
      enabled: true
      service-type: ClusterIP
  config:
    network:
      ingress-class: "kourier.ingress.networking.knative.dev"
    domain:
      knative.beansnet.net: ""
      dynamicdns.knative.beansnet.net: |
        selector:
          app: dynamicdns
  high-availability: 1
  workloads:
  - name: controller
    resources:
    - container: controller
      requests:
        cpu: "10m"
  - name: webhook
    resources:
    - container: webhook
      requests:
        cpu: "10m"
  - name: autoscaler
    resources:
    - container: autoscaler
      requests:
        cpu: "10m"
  - name: autoscaler-hpa
    resources:
    - container: autoscaler-hpa
      requests:
        cpu: "10m"
  - name: activator
    resources:
    - container: activator
      requests:
        cpu: "10m"
  - name: net-kourier-controller
    resources:
    - container: controller
      requests:
        cpu: "10m"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: knative-serving
  namespace: knative-serving
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns-prod
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: knative.beansnet.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kourier-internal
            port:
              name: http2
  - host: "*.knative.beansnet.net"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kourier-internal
            port:
              name: http2
  tls:
  - hosts:
    - knative.beansnet.net
    - "*.knative.beansnet.net"
    secretName: knative-cert-secret
