apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: knative-serving-cert
  namespace: istio-system
spec:
  secretName: knative-serving-cert
  commonName: knative.beansnet.net
  dnsNames:
  - knative.beansnet.net
  - "*.knative.beansnet.net"
  issuerRef:
    name: letsencrypt-dns-prod
    kind: ClusterIssuer
---
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  ingress:
    istio:
      enabled: true
      knative-ingress-gateway:
        selector:
          istio: ingress
        servers:
        - port:
            number: 443
            name: https
            protocol: HTTPS
          hosts:
          - knative.beansnet.net
          - "*.knative.beansnet.net"
          tls:
            mode: SIMPLE
            credentialName: knative-serving-cert
  config:
    domain:
      knative.beansnet.net: ""
    network:
      external-domain-tls: Enabled
      http-protocol: Redirected
      namespace-wildcard-cert-selector: |-
        matchExpressions:
        - key: "networking.knative.dev/disableWildcardCert"
          operator: "NotIn"
          values: ["true"]
    certmanager:
      issuerRef: |
        kind: ClusterIssuer
        name: letsencrypt-dns-prod
  high-availability:
    replicas: 1
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer # this issuer is specifically for Knative, it will use the CA stored in the secret created by the Certificate below
metadata:
  name: knative-selfsigned-issuer
spec:
  ca:
    secretName: knative-selfsigned-ca
---
apiVersion: cert-manager.io/v1
kind: Certificate # this creates a CA certificate, signed by cluster-selfsigned-issuer and stored in the secret knative-selfsigned-ca
metadata:
  name: knative-selfsigned-ca
  namespace: cert-manager #  If you want to use it as a ClusterIssuer the secret must be in the cert-manager namespace.
spec:
  secretName: knative-selfsigned-ca
  commonName: knative.dev
  usages:
    - server auth
  isCA: true
  issuerRef:
    kind: ClusterIssuer
    name: cluster-selfsigned-issuer