apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  ingress:
    istio:
      enabled: true
      knative-ingress-gateway:
        selector:
          istio: ingress
        servers:
        - port:
            number: 443
            name: https
            protocol: HTTPS
          hosts:
          - knative.beansnet.net
          - "*.knative.beansnet.net"
    domain:
      knative.beansnet.net: ""
  high-availability:
    replicas: 1
